### ISSUE TITLE
KESALAHAN

### ISSUE THREAD

**Issue by billalxcode** [kodingkeun/shorturl#27]
Halo pak, sepertinya saya menemukan beberapa masalah pada aplikasi ini. Salah satu nya yaitu saat masuk ke konsol / console yang ada di chrome, ada kesalahan yang tampil di konsol tersebut, seperti pada gambar dibawah

![Screenshot (132)](https://user-images.githubusercontent.com/71764176/196395813-66dc5d3c-f72c-43af-b7dd-3ac14d7fe64b.png)

**Comment by ibnusyawall** [comment]
issues fixed [#34 ](https://github.com/kodingkeun/shorturl/pull/34). please update the main shorturl project.
